apiVersion: v2
name: todobot
description: A Helm chart for TodoBot - AI-powered Todo Application with Chat Interface

# Application chart for TodoBot with frontend (Next.js), backend (FastAPI), and database (PostgreSQL)
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed.
appVersion: "1.0.0"
