{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "TodoBot.fullname" . }}-database
  labels:
    {{- include "TodoBot.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.database.service.type }}
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: {{ .Values.database.service.targetPort }}
    protocol: TCP
    name: postgres
  selector:
    {{- include "TodoBot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
