apiVersion: v1
kind: Secret
metadata:
  name: {{ include "TodoBot.fullname" . }}-secrets
  labels:
    {{- include "TodoBot.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database password
  database-password: {{ .Values.secrets.databasePassword | quote }}

  # Database URL (constructed from config)
  database-url: {{ printf "postgresql+asyncpg://%s:%s@%s-database:%s/%s" .Values.database.env.postgresUser .Values.secrets.databasePassword (include "TodoBot.fullname" .) (.Values.database.service.port | toString) .Values.database.env.postgresDb | quote }}

  # Better Auth Secret
  better-auth-secret: {{ .Values.secrets.betterAuthSecret | quote }}

  # LLM API Key
  llm-api-key: {{ .Values.secrets.llmApiKey | quote }}
